### ISSUE TITLE
          ^ Error: Cannot find module 'scss-tokenizer'

### ISSUE THREAD

**Issue by jason4wy** [Mirantis/ccp-contrail-pipeline#12]
make[1]: Entering directory `/root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core'
# We can't use make package directly because it tries to fetch third party
# from network which is not available during build
(cd /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core; \
	rm -f webroot/html/dashboard.html; \
	rm -f webroot/html/login.html; \
	rm -f webroot/html/login-error.html; \
	cp -a webroot/html/dashboard.tmpl webroot/html/dashboard.html; \
	cp -a webroot/html/login.tmpl webroot/html/login.html; \
	cp -a webroot/html/login-error.tmpl webroot/html/login-error.html; \
	./generate-files.sh 'prod-env' /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core);
Done, creating file: /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core/src/serverroot/common/url.routes.js
Done, creating file: /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core/src/serverroot/jobs/core/jobsCb.api.js
Done, creating file: /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core/src/serverroot/utils/url.routes.js
Done, creating file: /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core/src/serverroot/web/core/feature.list.js
Done, creating file: /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core/src/serverroot/web/routes/url.routes.js
Done, creating file: /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core/webroot/reports/qe/api/url.routes.js
Done, creating file: /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core/webroot/reports/udd/api/url.routes.js
error: ../controller/src/schema/all_cfg.xsd not found
error: json-schema files not generated
(cd /root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core; \
	./dev-install.sh;)

module.js:340
    throw err;
          ^
Error: Cannot find module 'scss-tokenizer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

module.js:340
    throw err;
          ^
Error: Cannot find module 'scss-tokenizer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core/contrail-web-core/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
make[1]: *** [override_dh_auto_build] Error 8
make[1]: Leaving directory `/root/oc/repos/ccp-contrail-pipeline/src/build/contrail-web-core'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc failed
make: *** [build-binary-contrail-web-core] Error 29

**Comment by Groundsea** [comment]
Hi jason4wy,
Did you solve this issue? I met this issue too.

**Comment by jason4wy** [comment]
resolved， but it was long time ago....

**Comment by chnyda** [comment]
Hey @Groundsea 
Which branch are you trying to use? For which distribution are you trying to make packages? Trusty?

**Comment by Groundsea** [comment]
@jason4wy, I solved it too, the reason is for network problem, the node_module download failed, I manully executed npm install to download those modules, and change the Makefile not to clean directory everytime, then it works.
@chnyda, Now I'm using OpenContrail R4.0, ubuntu is Trusty
